### ISSUE TITLE
NPM repository has old version of package.json

### ISSUE THREAD

**Issue by MoxiCult** [psychobolt/react-pie-menu#98]
NPM repository version has the following for peer dependencies 
`  "peerDependencies": {
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "styled-components": "^5.2.3"
  }`
but the Github version has
`  "peerDependencies": {
    "react": "^17.0.2 || ^18.0.0",
    "react-dom": "^17.0.2 || ^18.0.0",
    "styled-components": "^5.2.5"
  },`

As a result, I'm unable to update the react version in my project even though react-pie-menu apparently supports version ^8.0.0.

**Comment by psychobolt** [comment]
Hi try upgrade to [1.0.0-alpha.1](https://www.npmjs.com/package/react-pie-menu/v/1.0.0-alpha.1)

**Comment by MoxiCult** [comment]
> 1.0.0-alpha.1

Thank you, that resolved the issue!

**Comment by MoxiCult** [comment]
I may have spoken too soon. Although, the dependency conflict is resolved,
however I am getting the following error and I can't seem to figure out why

*Module not found: Can't resolve 'react-pie-menu' . *

If I downgrade back to 0.3.3 the error goes away.

I have confirmed that1.1.1-aplha.1 is installed and correctly identified in
package.json and package-lock.json. What could be different between the two
versions to cause the build to fail? It may be something local to my
project, but not sure what that could be be. I'm using next.js and
typescript.

-Jake

**Comment by MoxiCult** [comment]
Unfortunately, the repo is private. However, changing the import to direct resolution worked! I'm still not sure why that is the case. Like I said, it's odd that with the 0.3.3 version, the named module resolution works but not with 1.0.0-alpha.1. Regardless, importing from the direct  path like the following is a good enough work around for me. Thanks for your help and the great module!  

`import {
  PieMenu,
  PieCenter,
  Slice,
  //@ts-expect-error can not find declaration
} from '../../../node_modules/react-pie-menu';`

**Comment by keyserj** [comment]
Hi, I've run into the module issue as well and I think the problem is that the npm package's `dist` does not include any of the `index.dev.*` files, and the `package.json`'s `exports.development` configs [say to use the .dev files](https://github.com/psychobolt/react-pie-menu/blob/b1781789cc7ee0b739c7f8139a77581ad6777ec3/package.json#L8-L13).

You can see this reproduced on my branch https://github.com/keyserj/ameliorate/tree/pie-import-issue by cloning and running
```bash
cd web
npm i
npm run dev # open localhost:3000 and see the `module not found` error in devtools console and terminal output
# ctrl+c cancel running
npm run build # production build
npm run start # open localhost:3000 and a terribly-used-but-working react pie menu
```

I confirmed that `yarn build` creates the `dist/index.dev.*` files - I wonder if you published the package unintentionally without them, and just need to republish with them?

**Comment by psychobolt** [comment]
There is definitely a discrepancy between [alpha.0](https://www.runpkg.com/?react-pie-menu@1.0.0-alpha.0/dist/index.prod.cjs) and [alpha.1 ](https://www.runpkg.com/?react-pie-menu@1.0.0-alpha.1/dist/index.prod.cjs)although I don't believe your issue is related to the OP's. I will publish another version.

**Comment by psychobolt** [comment]
@keyserj Please try [1.0.0-alpha.2](https://www.npmjs.com/package/react-pie-menu/v/1.0.0-alpha.2)

**Comment by keyserj** [comment]
works 🔥 thanks!
